// This is file should only be used for testing

export const budgets = [
    {
        "id": "3a1ebb16-f8cf-4038-b1d9-85234d8b455c",
        "name": "Q1 2021 Budget",
        "last_modified_on": "2021-03-17T04:22:06+00:00",
        "first_month": "2020-10-01",
        "last_month": "2021-03-01",
        "date_format": {
            "format": "MM/DD/YYYY"
        },
        "currency_format": {
            "iso_code": "USD",
            "example_format": "123,456.78",
            "decimal_digits": 2,
            "decimal_separator": ".",
            "symbol_first": true,
            "group_separator": ",",
            "currency_symbol": "$",
            "display_symbol": true
        }
    }
]

export const accounts = [
    {
        "id": "dccda20d-430f-47b2-879a-8ea028bb84f8",
        "name": "Checking",
        "type": "checking",
        "on_budget": true,
        "closed": false,
        "note": null,
        "balance": 1222720,
        "cleared_balance": 0,
        "uncleared_balance": 1222720,
        "transfer_payee_id": "8a97e9ba-bc57-4e30-a044-6a8469efd6b4",
        "direct_import_linked": true,
        "direct_import_in_error": false,
        "deleted": false
    },
    {
        "id": "32c248ca-3eb7-4660-9932-4dce7a039d00",
        "name": "Checking #2",
        "type": "checking",
        "on_budget": true,
        "closed": false,
        "note": null,
        "balance": -120000,
        "cleared_balance": -35000,
        "uncleared_balance": -85000,
        "transfer_payee_id": "8feca7df-d59f-40a4-8ca9-47f21b150bb4",
        "direct_import_linked": true,
        "direct_import_in_error": false,
        "deleted": false
    }
]

export const categories = [
    {
        "id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
        "name": "Immediate Obligations",
        "hidden": false,
        "deleted": false,
        "categories": [
            {
                "id": "0686e377-da87-4de3-a5f5-a703ef920bfa",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "🏠 Mortgage",
                "hidden": false,
                "original_category_group_id": null,
                "note": "",
                "budgeted": 0,
                "activity": 0,
                "balance": 2126510,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 215000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 2126510,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "943fd42f-0cb5-4725-b35a-497324918117",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "⚡ Electric, Water, & Sewer",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": -192250,
                "balance": 257750,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 75000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 450000,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "747f88de-95b4-4b39-9fbe-74c49328c4fa",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "🔥 Gas (Utility)",
                "hidden": false,
                "original_category_group_id": null,
                "note": "Analyze the median cost",
                "budgeted": 0,
                "activity": 0,
                "balance": 91930,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 12500,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 91930,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "e60c04d2-627e-44d9-bdb4-3c047b44f82c",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "📶 Internet",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 202490,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 22500,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 202490,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "0b102df1-c291-476e-a2f3-e5b6e23fdfa0",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "🛒 Groceries",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 1133330,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 200000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 1133330,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "d5f0a876-8c14-44bf-b0c5-36e29b4ec206",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "🦴 Dogs / Cats 🧶",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 150000,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 30000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 150000,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "f42a01ba-f392-4e0c-ab3d-206c9248f066",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "➕ Car Insurance",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 96910,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            },
            {
                "id": "0e3ec719-7a29-40ee-be8a-a3720456a73f",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "⛽ Transportation",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 105360,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            },
            {
                "id": "b2406e90-5016-4eb7-81e2-1a86d5d03093",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "📱 Cell Phone",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 138000,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 23000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 138000,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "af8df22f-c5db-4da6-b1d3-0e512f2c9be3",
                "category_group_id": "b6b449e0-3ba0-48eb-9adf-3ae5b4c76b0c",
                "name": "🎒 Preschool",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": -85000,
                "balance": 22500,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 21250,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 107500,
                "goal_overall_left": 0,
                "deleted": false
            }
        ]
    },
    {
        "id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
        "name": "True Expenses",
        "hidden": false,
        "deleted": false,
        "categories": [
            {
                "id": "b73c69de-debf-40b3-bc58-fefdeb7fd4d7",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "🔧 Auto Maintenance",
                "hidden": false,
                "original_category_group_id": null,
                "note": "Any auto maintenance, such as mechanical work, registration, and licensing fees. TB was $150",
                "budgeted": 0,
                "activity": 0,
                "balance": 514250,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 35000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 514250,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "e5c2d406-947d-4100-a53a-5150a34ae2b5",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "🔨 Home Maintenance",
                "hidden": false,
                "original_category_group_id": null,
                "note": "TB was 1300",
                "budgeted": 0,
                "activity": 0,
                "balance": 2310040,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-19",
                "goal_target": 125000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 2310040,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "3554aac2-dc98-4412-9b1d-9c9a83b1fb7f",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "🐶 Pet Care",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 85000,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-19",
                "goal_target": 25000,
                "goal_target_month": null,
                "goal_percentage_complete": 85,
                "goal_months_to_budget": 1,
                "goal_under_funded": 15000,
                "goal_overall_funded": 85000,
                "goal_overall_left": 15000,
                "deleted": false
            },
            {
                "id": "cb0f4725-ed43-4a2e-8931-d89624d57207",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "👕 Clothing",
                "hidden": false,
                "original_category_group_id": null,
                "note": "TB was $25",
                "budgeted": 0,
                "activity": 0,
                "balance": 103000,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 25000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 103000,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "176efca6-2992-4652-ae44-f7ef20e2ebae",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "🎄 Christmas",
                "hidden": false,
                "original_category_group_id": null,
                "note": "",
                "budgeted": 0,
                "activity": 0,
                "balance": 1577880,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 50000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 1577880,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "42826453-8061-4d54-8c22-bc63b88556f5",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "🎁 Gifts",
                "hidden": false,
                "original_category_group_id": null,
                "note": "TB was $20",
                "budgeted": 0,
                "activity": 0,
                "balance": 100960,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-01",
                "goal_target": 20000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 100960,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "d6665973-9594-4815-8263-053cdf880ea7",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "👨‍💻 Software Subscriptions",
                "hidden": false,
                "original_category_group_id": null,
                "note": "",
                "budgeted": 0,
                "activity": -7500,
                "balance": 299600,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-19",
                "goal_target": 20000,
                "goal_target_month": null,
                "goal_percentage_complete": 100,
                "goal_months_to_budget": 1,
                "goal_under_funded": 0,
                "goal_overall_funded": 307100,
                "goal_overall_left": 0,
                "deleted": false
            },
            {
                "id": "469e5dda-a346-4e5d-8ca1-bd02dfdb30ca",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "💰 Safety Net",
                "hidden": false,
                "original_category_group_id": null,
                "note": "Typically $150 a week. Transfer balance was $1160",
                "budgeted": 0,
                "activity": 0,
                "balance": 0,
                "goal_type": "TB",
                "goal_creation_month": "2020-11-01",
                "goal_target": 10000000,
                "goal_target_month": null,
                "goal_percentage_complete": 0,
                "goal_months_to_budget": 0,
                "goal_under_funded": 0,
                "goal_overall_funded": 0,
                "goal_overall_left": 10000000,
                "deleted": false
            },
            {
                "id": "7404892c-4543-4f40-a95b-3cbb08592714",
                "category_group_id": "ef66594c-f7ae-48ce-9e79-aa51f473c712",
                "name": "❓ Stuff I Forgot to Budget For",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 34730,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-19",
                "goal_target": 10000,
                "goal_target_month": null,
                "goal_percentage_complete": 86,
                "goal_months_to_budget": 1,
                "goal_under_funded": 5270,
                "goal_overall_funded": 34730,
                "goal_overall_left": 5270,
                "deleted": false
            }
        ]
    },
    {
        "id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
        "name": "Quality of Life Goals",
        "hidden": false,
        "deleted": false,
        "categories": [
            {
                "id": "2a51ac66-93c5-498e-aa81-ad1979aea2bc",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "🚢 Vacation",
                "hidden": false,
                "original_category_group_id": null,
                "note": "",
                "budgeted": 0,
                "activity": 0,
                "balance": 100000,
                "goal_type": "NEED",
                "goal_creation_month": "2020-11-19",
                "goal_target": 100000,
                "goal_target_month": null,
                "goal_percentage_complete": 25,
                "goal_months_to_budget": 1,
                "goal_under_funded": 300000,
                "goal_overall_funded": 100000,
                "goal_overall_left": 300000,
                "deleted": false
            },
            {
                "id": "5b196428-6b23-4ae7-ba3e-3f51a7612c88",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "📖 Books",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 0,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            },
            {
                "id": "90876762-eb4b-4ffe-bc4e-91fcaf696ef5",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "🪔 Essential Oils",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 0,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            },
            {
                "id": "1b9cb6a9-ba62-4606-ba6f-a2b180f59f74",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "👧🏽 Lola",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 10000,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            },
            {
                "id": "6b3c4d63-beba-4f13-b972-f68b644323c3",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "⌚ Watch",
                "hidden": false,
                "original_category_group_id": null,
                "note": "$50 a week. Transfer balance was $116",
                "budgeted": 0,
                "activity": 0,
                "balance": 47250,
                "goal_type": "TB",
                "goal_creation_month": "2020-11-01",
                "goal_target": 4000000,
                "goal_target_month": null,
                "goal_percentage_complete": 1,
                "goal_months_to_budget": 0,
                "goal_under_funded": 0,
                "goal_overall_funded": 47250,
                "goal_overall_left": 3952750,
                "deleted": false
            },
            {
                "id": "e1bee051-a8a6-4712-8e06-c6292b265d0a",
                "category_group_id": "714d905a-b7f2-4172-a70d-f130b75f3e49",
                "name": "💅 Chloe Pamper",
                "hidden": false,
                "original_category_group_id": null,
                "note": null,
                "budgeted": 0,
                "activity": 0,
                "balance": 372330,
                "goal_type": null,
                "goal_creation_month": null,
                "goal_target": 0,
                "goal_target_month": null,
                "goal_percentage_complete": null,
                "goal_months_to_budget": null,
                "goal_under_funded": null,
                "goal_overall_funded": null,
                "goal_overall_left": null,
                "deleted": false
            }
        ]
    }
]

export const payees = [
    {
        "id": "31169895-5088-44dd-b2e6-cfa233b6eb91",
        "name": "GRAND TRAV RSRT RETAIL",
        "transfer_account_id": null,
        "deleted": false
    },
    {
        "id": "cf32ae5c-6892-4c1e-a87e-634694fefbf5",
        "name": "TST* KORA BREW HOUSE &",
        "transfer_account_id": null,
        "deleted": false
    },
    {
        "id": "2be1b41c-8e0e-4f6f-b03a-d5ffef1e22f6",
        "name": "AUTO IMAGES LLC",
        "transfer_account_id": null,
        "deleted": false
    },
    {
        "id": "62e47afd-586b-4d6b-9c3a-b69da5dee156",
        "name": "AMAZON.COM*MK4FA7JG1",
        "transfer_account_id": null,
        "deleted": false
    },
    {
        "id": "98145711-23de-4ab9-91b9-46c1ae9a51a3",
        "name": "McDonald's",
        "transfer_account_id": null,
        "deleted": false
    }
]